### ISSUE TITLE
Generating unit tests does not work

### ISSUE THREAD

**Issue by VladIftime** [flexiblepower/s2-python#57]
The current version of `development_utilities/gen_unit_test_template.py` does not run. Current error:
`Traceback (most recent call last):
  File "/Users/vladiftime/Documents/SEITA_Vlad/s2-python/development_utilities/gen_unit_test_template.py", line 267, in <module>
    assert_test_data = dump_test_data_as_constructor_field_for(
  File "/Users/vladiftime/Documents/SEITA_Vlad/s2-python/development_utilities/gen_unit_test_template.py", line 194, in dump_test_data_as_constructor_field_for
    raise RuntimeError(
RuntimeError: Please implement dump test data for field type typing_extensions.Literal['FRBC.ActuatorStatus']
(s2-env) `

**Comment by Flix6x** [comment]
Did you get further with this issue? If so, what fixed it? If not, what progress did we make and where are we currently stuck?

**Comment by VladIftime** [comment]
The problem is solved in the PR #59
